ObjectsCategories = [   12,0;...
                        13,0;...
                        12,0;...
                        12,0;...
                        11,0;...
                        12,0;...
                        13,0;...
                        13,0;...
                        15,1;...
                        14,1;...
                        13,1;...
                        16,1;...
                        14,1;...
                        15,1;...
                        13,1;...
                        13,2;...
                        13,2;...
                        14,2;...
                        13,2;...
                        14,2;...
                        19,3;...
                        14,4;...
                        15,5];
            
            
fileObjects = fopen('gtObjects.txt','w');
fileCategories = fopen('gtCategories.txt','w');
% to solve the enter in the end
fprintf(fileObjects,'%d', 0);
fprintf(fileCategories,'%d', ObjectsCategories(1,2));
fprintf(fileObjects,'\n%d', ones(ObjectsCategories(1,1)-1,1).*0);
fprintf(fileCategories,'\n%d', ones(ObjectsCategories(1,1)-1,1).*ObjectsCategories(1,2));
for i=2:length(ObjectsCategories)
fprintf(fileObjects,'\n%d', ones(ObjectsCategories(i,1),1).*i-1);
fprintf(fileCategories,'\n%d', ones(ObjectsCategories(i,1),1).*ObjectsCategories(i,2));
end


fclose(fileObjects);
fclose(fileCategories);


